### ISSUE TITLE
error getting while running pls help here

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [videogameboy76/frozenbubbleandroid#49]
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.peculiargames.andmodplug.PlayerThread.ModPlug_JUnload() (tried Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1JUnload and Java_com_peculiargames_andmodplug_PlayerThread_ModPlug_1JUnload__)
                                                                             at com.peculiargames.andmodplug.PlayerThread.ModPlug_JUnload(Native Method)
                                                                             at com.peculiargames.andmodplug.PlayerThread.unLoadMod(PlayerThread.java:845)

**Comment by videogameboy76** [comment]
You need to install the NDK.
